apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  "3306": "airoad/mysql-external:3306"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysql-tcp
  namespace: airoad
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/tcp-services-configmap: ingress-nginx/tcp-services
spec:
  rules:
  - host: db.luigi99.cloud
