apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: airoad
spec:
  selector:
    role: master
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  namespace: airoad
spec:
  selector:
    app: mysql-master
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-master-headless
  namespace: airoad
spec:
  selector:
    app: mysql-master
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-external
  namespace: airoad
spec:
  selector:
    role: master
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30307
    name: mysql
  type: NodePort
