apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-master-config
  namespace: airoad
data:
  my.cnf: |
    [mysqld]
    default_authentication_plugin=mysql_native_password
    bind-address=0.0.0.0
    server-id=1
    log-bin=mysql-bin
    binlog-format=ROW
    gtid-mode=ON
    enforce-gtid-consistency=ON
    log-slave-updates=ON
    read-only=OFF
    super-read-only=OFF
    max_connections=200
    innodb_buffer_pool_size=512M
    innodb_log_file_size=256M
    innodb_flush_log_at_trx_commit=1
    sync_binlog=1
    expire_logs_days=7
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
