apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-master
  namespace: airoad
spec:
  serviceName: mysql-master-headless
  replicas: 1
  selector:
    matchLabels:
      app: mysql-master
  template:
    metadata:
      labels:
        app: mysql-master
        role: master
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: mysql-master
          image: mysql:8.0.43
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-master-storage
              mountPath: /var/lib/mysql
            - name: mysql-master-config
              mountPath: /etc/mysql/conf.d
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - mysql -h localhost -u root -p"$MYSQL_ROOT_PASSWORD" -e "SELECT 1"
            initialDelaySeconds: 10
            timeoutSeconds: 1
      volumes:
        - name: mysql-master-config
          configMap:
            name: mysql-master-config
  volumeClaimTemplates:
    - metadata:
        name: mysql-master-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: longhorn
        resources:
          requests:
            storage: 1Gi