apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-master-config
  namespace: airoad
data:
  postgresql.conf: |
    # Connection Settings
    listen_addresses = '*'
    max_connections = 200

    # Memory Settings
    shared_buffers = 256MB
    effective_cache_size = 1GB
    maintenance_work_mem = 64MB
    work_mem = 2MB

    # WAL Settings
    wal_level = replica
    max_wal_senders = 10
    max_replication_slots = 10
    wal_keep_size = 1GB

    # Logging
    log_timezone = 'UTC'
    log_statement = 'none'
    log_duration = off
    log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '

    # Locale and Formatting
    datestyle = 'iso, mdy'
    timezone = 'UTC'
    lc_messages = 'en_US.utf8'
    lc_monetary = 'en_US.utf8'
    lc_numeric = 'en_US.utf8'
    lc_time = 'en_US.utf8'
    default_text_search_config = 'pg_catalog.english'

    # Extensions
    shared_preload_libraries = 'pg_stat_statements,vector'

  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    host    all             all             0.0.0.0/0               md5
    host    replication     all             0.0.0.0/0               md5
