apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: airoad
spec:
  selector:
    role: master
  ports:
  - port: 5432
    targetPort: 5432
    name: postgresql
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-master
  namespace: airoad
spec:
  selector:
    app: postgresql-master
  ports:
  - port: 5432
    targetPort: 5432
    name: postgresql
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-master-headless
  namespace: airoad
spec:
  selector:
    app: postgresql-master
  ports:
  - port: 5432
    targetPort: 5432
    name: postgresql
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-external
  namespace: airoad
spec:
  selector:
    role: master
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30432
    name: postgresql
  type: NodePort
